import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import ReactQueryProvider from '@/providers/QueryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // style={{ backgroundColor: '#000' }}
        className={``}
      >
        <ReactQueryProvider>
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
          <ReactQueryDevtools initialIsOpen={false} />
        </ReactQueryProvider>
      </body>
    </html>
  );
}

/*
   <body
        // style={{ backgroundColor: '#000' }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

*/
